Repository smn-hrtzsch/SPS, pull requests merged in 2024-07, with the labels that each got.

#18 Created the Enums ScheduleTypes & MatchTypes
  src/ClassLib/Enums.cs
Labels: enhancement

#19 Class structure Emailservice class
  src/ClassLib/EmailService.cs
Labels: enhancement

#20 class structure Prediction game class
  src/ClassLib/PredictionGame.cs
Labels: enhancement

#16 Class structure Score class
  src/ClassLib/Score.cs
Labels: enhancement

#15 Class structure FootballPrediction class
  src/ClassLib/FootballPrediction.cs
Labels: enhancement

#12 Class structure FootballMatch class
  src/ClassLib/FootballMatch.cs
Labels: enhancement

#17 Class structure Member class
  src/ClassLib/EmailService.cs
  src/ClassLib/Enums.cs
  src/ClassLib/Member.cs
  src/ClassLib/PredictionGame.cs
  src/ClassLib/Schedule.cs
Labels: enhancement, good first issue

#25 Implement CSV File IO
  csv-files/EM_2024.csv
  src/ClassLib.Tests/UnitTest1.cs
  src/ClassLib/CSVReader.cs
  src/ClassLib/CSVWriter.cs
  src/ClassLib/Enums.cs
  src/ClassLib/FootballMatch.cs
  src/ClassLib/Match.cs
Labels: documentation, enhancement

#30 Added Emailservice Features
  src/ClassLib/EmailService.cs
Labels: enhancement

#31 Implement Prediction class functionality
  src/ClassLib.Tests/TestPredictionClass.cs
  src/ClassLib.Tests/UnitTest1.cs
  src/ClassLib/FootballPrediction.cs
  src/ClassLib/Prediction.cs
Labels: enhancement

#37 Implementation of Score Calculation
  src/ClassLib.Tests/MemberTest.cs
  src/ClassLib.Tests/TestPredictionClass.cs
  src/ClassLib.Tests/UnitTest1.cs
  src/ClassLib/CSVReader.cs
  src/ClassLib/CSVWriter.cs
  src/ClassLib/FootballMatch.cs
  src/ClassLib/FootballPrediction.cs
  src/ClassLib/Match.cs
  src/ClassLib/MatchFactory.cs
  src/ClassLib/Member.cs
  src/ClassLib/PredictionGame.cs
  src/ClassLib/Schedule.cs
  src/ClassLib/Score.cs
Labels: enhancement

#38 Implement test method for CalculateScores() in Member class
  src/ClassLib.Tests/MemberTest.cs
  src/ClassLib/Member.cs
  src/ClassLib/Score.cs
Labels: enhancement

#39 Expanded File IO to save member data in csv files
  src/ClassLib.Tests/MemberScoresTest.csv
  src/ClassLib.Tests/MembersTest.csv
  src/ClassLib.Tests/TestCsvFileIO.cs
  src/ClassLib.Tests/TestMember.cs
  src/ClassLib.Tests/UnitTest1.cs
  src/ClassLib/CSVWriter.cs
  src/ClassLib/Member.cs
  src/ClassLib/PredictionGame.cs
  src/ClassLib/Score.cs
Labels: enhancement

#40 Added EmailService features, Modified Programm.cs and Implemented PredictionGame.cs ctor and functions
  .github/workflows/csharpier-formatting.yml
  .github/workflows/emailroutine-daily-and-weekly.yaml
  src/ClassLib.Tests/TestCsvFileIO.cs
  src/ClassLib.Tests/TestMember.cs
  src/ClassLib.Tests/TestPredictionGame.cs
  src/ClassLib/CSVWriter.cs
  src/ClassLib/EmailService.cs
  src/ClassLib/Enums.cs
  src/ClassLib/Member.cs
  src/ClassLib/PredictionGame.cs
  src/EmailContinuousIntegration/EmailCIPipeline.cs.csproj
  src/EmailContinuousIntegration/Program.cs
  src/Program/Program.cs
  src/src.sln
Labels: documentation, enhancement, help wanted

#44 Completed all required File IO features
  src/ClassLib.Tests/MemberPredictionsTest.csv
  src/ClassLib.Tests/MemberScoresTest.csv
  src/ClassLib.Tests/MembersTest.csv
  src/ClassLib.Tests/TestCsvFileIO.cs
  src/ClassLib.Tests/TestMember.cs
  src/ClassLib.Tests/TestPredictionGame.cs
  src/ClassLib/CSVReader.cs
  src/ClassLib/CSVWriter.cs
  src/ClassLib/FootballMatch.cs
  src/ClassLib/Member.cs
  src/ClassLib/Prediction.cs
  src/ClassLib/PredictionGame.cs
  src/ClassLib/Schedule.cs
  src/ClassLib/Score.cs
Labels: enhancement

#46 Implemented first console app
  csv-files/EM_2024.csv
  csv-files/MemberData.csv
  src/ClassLib/CSVReader.cs
  src/ClassLib/CSVWriter.cs
  src/ClassLib/FootballPrediction.cs
  src/ClassLib/Member.cs
  src/ClassLib/Prediction.cs
  src/ClassLib/PredictionGame.cs
  src/EmailContinuousIntegration/ContinuousIntegration.cs
  src/Program/Program.cs
  src/Program/Program.sln
Labels: enhancement

#52 Program impmented
  README.md
  src/ClassLib.Tests/TestCsvFileIO.cs
  src/ClassLib.Tests/TestPredictionClass.cs
  src/ClassLib.Tests/TestPredictionGame.cs
  src/ClassLib/CSVReader.cs
  src/ClassLib/CSVWriter.cs
  src/ClassLib/FootballMatch.cs
  src/ClassLib/FootballPrediction.cs
  src/ClassLib/Member.cs
  src/ClassLib/Prediction.cs
  src/Program/Program.cs
Labels: enhancement

#55 First Release Merge
  .github/workflows/csharpier-formatting.yml
  .github/workflows/emailroutine-daily.yml
  .github/workflows/generate-docs.yml
  Doxyfile
  README.md
  csv-files/EM_2024.csv
  csv-files/MemberData.csv
  src/ClassLib.Tests/EM_2024Test.csv
  src/ClassLib.Tests/MemberPredictionsTest.csv
  src/ClassLib.Tests/MemberScoresTest.csv
  src/ClassLib.Tests/MembersTest.csv
  src/ClassLib.Tests/TestCsvFileIO.cs
  src/ClassLib.Tests/TestMember.cs
  src/ClassLib.Tests/TestPredictionClass.cs
  src/ClassLib.Tests/TestPredictionGame.cs
  src/ClassLib.Tests/UnitTest1.cs
  src/ClassLib/CSVReader.cs
  src/ClassLib/CSVWriter.cs
  src/ClassLib/Class1.cs
  src/ClassLib/EmailService.cs
  src/ClassLib/Enums.cs
  src/ClassLib/FootballMatch.cs
  src/ClassLib/FootballPrediction.cs
  src/ClassLib/Match.cs
  src/ClassLib/MatchFactory.cs
  src/ClassLib/Member.cs
  src/ClassLib/Prediction.cs
  src/ClassLib/PredictionGame.cs
  src/ClassLib/Schedule.cs
  src/ClassLib/Score.cs
  src/EmailContinuousIntegration/ContinuousIntegration.cs
  src/EmailContinuousIntegration/EmailCIPipeline.cs.csproj
  src/Program/Program.cs
  src/Program/Program.csproj
  src/Program/Program.sln
  src/src.sln
Labels: enhancement
